App/views.py
import hashlib
import random
import re

from flask import Blueprint, render_template, request, g, session, redirect, url_for
from App.models import Article, db, Article_list, Admin

blue = Blueprint('blue', __name__)

#加密方法
def md5_password(password):
    m = hashlib.md5()
    m.update(password.encode())
    return  m.hexdigest()
    pass


@blue.route('/',methods=["GET","POST"])
def index():
    aa = Article()
    articlelist = aa.query.all()
    g.articlelist=articlelist
    bb = Article_list()
    articlelists = bb.query.all()
    g.articlelists=articlelists

    if request.method == 'POST':
        if request.form['keyboard']:
            search_data = request.form['keyboard']

            articlelists = Article_list.query.filter(Article_list.title.contains(search_data))
            if not articlelists:
                return 'nothing find'
        else:
            # 404收入为空
            return render_template('nothingGetForSearch.html')
    return render_template('index.html',articlelist = articlelist, articlelists = articlelists)

@blue.route('/check/',methods=["GET","POST"])
def check():
    p=Article()
    articlelist = p.query.all()
    check_mark = request.form.get('keyboard')
    articlelists = Article_list.query.filter(Article_list.title.contains(check_mark))

    print(request.form.get('keyboard'))
    return render_template('index.html', articlelist=articlelist, articlelists=articlelists)

@blue.route('/check/<ccheck>/',methods=["GET","POST"])
def checkdata(ccheck):
    p=Article()
    articlelist = p.query.all()

    articlelists = Article_list.query.filter(Article_list.type==ccheck)

    return render_template('index.html', articlelist=articlelist, articlelists=articlelists)


@blue.route('/search/',methods=["GET","POST"])
def search():
    p=Article()
    data = p.query.all()
    print(data)
    return "ok"


@blue.route('/admin/')
def admin_login():
    return render_template('admin_login.html')

@blue.route('/admin_index/',methods=["GET","POST"])
def admin_index():
    if request.method == "POST":
        username = request.form.get('username')
        userpassword = md5_password(request.form.get('userpwd'))

        person = Admin.query.filter(Admin.name==username)

        if person.first():
            t=person.first().password.replace("\n","")

            if t == userpassword:
                print(1)
                session['username'] = username
                # 要使用session加密和md5加密和用戶名登錄有效时间
                session['password'] = userpassword
                #考虑密码错误后加入验证码
                return render_template('admin_index.html', username=username)

        return render_template('admin_login.html')
    else:
        tempdata=session.get('username','')
        print(tempdata)
        if not tempdata:
            return render_template('admin_login.html')
        return render_template('admin_index.html', username=tempdata)

@blue.route('/admin_index/article/',methods=["GET","POST"])
def article():
    tempdata=session.get('username','')
    if not tempdata:
        return render_template('admin_login.html')

    articlelists = Article_list.query.all()
    return render_template('article.html',articlelists=articlelists)

@blue.route('/admin_index/article_add/',methods=["GET","POST"])
def article_add():
    tempdata=session.get('username','')
    if not tempdata:
        return render_template('admin_login.html')
    if request.method == "POST" :
        newArticle = Article_list()
        newArticle.title = request.form.get('title')
        newArticle.content = request.form.get('content')[3:-3]
        newArticle.type = request.form.get('category')
        newArticle.pic = random.randint(1,11)
        try:
            db.session.add(newArticle)
            db.session.commit()

        except:
            db.session.rollback()
            db.session.flush()
            return  "error"
        articlelists = Article_list.query.all()
        return render_template('article.html', articlelists=articlelists)
    p = Article()
    articlelist = p.query.all()
    return render_template('add-article.html',articlelist = articlelist)


@blue.route('/admin_index/article_update/<titlename>/',methods=["GET","POST"])
def article_update(titlename):
    #titlename更新文章的名称，作为标志
    tempdata=session.get('username','')
    if not tempdata:
        return render_template('admin_login.html')
    #更改的文章
    if request.method == "POST" :
        updateArticle =Article_list.query.filter_by(title = request.form.get("title","")).first()
        #判断内容是否有更改not
        updateArticle.title = request.form.get('title')
        updateArticle.content = re.findall(r"<p>(.*)</p>",request.form.get('content'))
        print(updateArticle.content)
        updateArticle.type = request.form.get('category')

        try:
            db.session.commit()

        except:
            db.session.rollback()
            db.session.flush()
            return  "error"
        articlelists = Article_list.query.all()
        return render_template('article.html', articlelists=articlelists)

    #显示更改条目
    articlelists = Article_list.query.filter_by(title=titlename)
    p = Article()
    articlelist = p.query.all()
    #保存checked标签
    data=[]
    #print(type(articlelists.first()),articlelists.first(),articlelists.first().title)
    for i in articlelist:
        #print(i.block_article,articlelists.first().type)
        if i.block_article == articlelists.first().type :
            data.append({"title":i.block_article,'mark':"checked"})
        else:
            data.append({"title":i.block_article,'mark':""})
    print(articlelists.first().title)
    return render_template('update-article.html',articlelist = data,articlelists=articlelists.first())

@blue.route('/admin_index/article_del/',methods=["GET","POST"])
def article_del():
    tempdata=session.get('username','')
    if not tempdata:
        return render_template('admin_login.html')
    if request.method == "POST" :

        values1 = list(request.form.to_dict().values())
        for del_art in values1:
            del_article = Article_list.query.filter_by(title=del_art)
            try:
                db.session.delete(del_article)
                db.session.commit()

            except:
                db.session.rollback()
                db.session.flush()
                return  "error"
    if request.method =="delete":

        pass
    return redirect(url_for('blue.article'))


@blue.route('/admin_index/article_delone/<data>/', methods=["GET","delete"])
def article_delone(data):
    tempdata = session.get('username', '')
    if not tempdata:
        return render_template('admin_login.html')

    del_article = Article_list.query.filter_by(title=data).first()
    print(del_article.title)
    try:
        db.session.delete(del_article)
        db.session.commit()

    except:
        db.session.rollback()
        db.session.flush()
        return "error"
    return redirect(url_for('blue.article'))


@blue.route('/admin_index/category/',methods=["POST","GET"])
def category():
    tempdata = session.get('username', '')
    if not tempdata:
        return render_template('admin_login.html')
    if request.method == "POST":
        return "change"
    #栏目总数，数目顺序,单个所拥有的article数目,别名
    data_category = []
    mark_category = 0
    articlelist = Article.query.all()
    for detail in articlelist:
        mark_category += 1
        count = Article_list.query.filter(Article_list.type == detail.block_article).count()
        data_category.append({"id":mark_category,"name":detail.block_article,"count":count,"smallname":"无"})

    return render_template('category.html',articlelist=data_category,mark_category = mark_category)


@blue.route('/admin_index/category_add',methods=["GET","POST"])
def category_add():

    tempdata=session.get('username','')
    if not tempdata:
        return render_template('admin_login.html')
    if request.method == "POST" :
        newCategory = Article()
        newCategory.block_article = request.form.get("name")
        try:
            db.session.add(newCategory)
            db.session.commit()

        except:
            db.session.rollback()
            db.session.flush()
            return  "error"

    return redirect(url_for('blue.category'))


@blue.route('/admin_index/category_update/<titlename>/',methods=["GET","POST"])
def category_update(titlename):
    #titlename更新文章的名称，作为标志
    tempdata=session.get('username','')
    if not tempdata:
        return render_template('admin_login.html')
    #更改的文章

    if request.method == "POST" :

        updateCategory =Article_list.query.filter_by(block_article = titlename).first()
        #判断内容是否有更改not
        updateCategory.block_article = request.form.get('name')

        try:
            db.session.commit()

        except:
            db.session.rollback()
            db.session.flush()
            return  "error"

        return redirect('url_for(blue.category)')

    #显示更改条目
    articlelist = Article.query.filter_by(block_article=titlename).first()
    data = Article.query.all()
    return render_template('update-category.html',articlelist = articlelist,data = data)


@blue.route('/admin_index/category_del/<titlename>/')
def category_del(titlename):
    tempdata=session.get('username','')

    if not tempdata:
        return render_template('admin_login.html')



    del_article = Article.query.filter_by(block_article=titlename).first()
    try:
        db.session.delete(del_article)
        db.session.commit()

    except:
        db.session.rollback()
        db.session.flush()
        return  "error"

    return redirect(url_for('blue.category'))


@blue.route('/manager/')
def get():


App/templates/add-category.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>无标题文档</title>
</head>

<body>
</body>
</html>

App/templates/admin_login.html
<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="renderer" content="webkit">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>异清轩博客管理系统</title>
<link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="/static/css/style.css">
<link rel="stylesheet" type="text/css" href="/static/css/login.css">
<link rel="apple-touch-icon-precomposed" href="/static/images/icon/icon.png">
<link rel="shortcut icon" href="/static/images/icon/favicon.ico">
<script src="/static/js/jquery-2.1.4.min.js"></script>
<!--[if gte IE 9]>
  <script src="/static/js/jquery-1.11.1.min.js" type="text/javascript"></script>
  <script src="/static/js/html5shiv.min.js" type="text/javascript"></script>
  <script src="/static/js/respond.min.js" type="text/javascript"></script>
  <script src="/static/js/selectivizr-min.js" type="text/javascript"></script>
<![endif]-->
<!--[if lt IE 9]>
  <script>window.location.href='upgrade-browser.html';</script>
<![endif]-->
</head>

<body class="user-select">
<div class="container">
  <div class="siteIcon"><img src="/static/images/icon/icon.png" alt="" data-toggle="tooltip" data-placement="top" title="欢迎使用异清轩博客管理系统" draggable="false" /></div>
  <form action="{{ url_for('blue.admin_index') }}" method="post" autocomplete="off" class="form-signin">
    <h2 class="form-signin-heading">管理员登录</h2>
    <label for="userName" class="sr-only">用户名</label>
    <input type="text" id="userName" name="username" class="form-control" placeholder="请输入用户名" required autofocus autocomplete="off" maxlength="10">
    <label for="userPwd" class="sr-only">密码</label>
    <input type="password" id="userPwd" name="userpwd" class="form-control" placeholder="请输入密码" required autocomplete="off" maxlength="18">
    <a href="main.html"><button class="btn btn-lg btn-primary btn-block" type="submit" id="signinSubmit">登录</button></a>
  </form>
  <div class="footer">
    <p><a href="index.html" data-toggle="tooltip" data-placement="left" title="不知道自己在哪?">回到后台 →</a></p>
  </div>
</div>
<script src="/static/js/bootstrap.min.js"></script>
<script>
$('[data-toggle="tooltip"]').tooltip();
window.oncontextmenu = function(){
	//return false;
};
$('.siteIcon img').click(function(){
	window.location.reload();
});
$('#signinSubmit').click(function(){
	if($('#userName').val() === ''){
		$(this).text('用户名不能为空');
	}else if($('#userPwd').val() === ''){
		$(this).text('密码不能为空');
	}else{
		$(this).text('请稍后...');
	}
});
</script>
</body>
</html>

App/templates/nothingGetForSearch.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>$Title$</title>
</head>
<body>
<div style="width: 300px;height: 100px;position: absolute;left: 100px;top: 50px;overflow: hidden">
    <p>从前有座山，山里有个服务器，</p>
    <p>服务器不想鸟你</p>

</div>
</body>
</html>

App/templates/update-category.html
<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="renderer" content="webkit">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>修改栏目 - 异清轩博客管理系统</title>
<link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="/static/css/style.css">
<link rel="stylesheet" type="text/css" href="/static/css/font-awesome.min.css">
<link rel="apple-touch-icon-precomposed" href="/static/images/icon/icon.png">
<link rel="shortcut icon" href="/static/images/icon/favicon.ico">
<script src="/static/js/jquery-2.1.4.min.js"></script>
<!--[if gte IE 9]>
  <script src="js/jquery-1.11.1.min.js" type="text/javascript"></script>
  <script src="js/html5shiv.min.js" type="text/javascript"></script>
  <script src="js/respond.min.js" type="text/javascript"></script>
  <script src="js/selectivizr-min.js" type="text/javascript"></script>
<![endif]-->
<!--[if lt IE 9]>
  <script>window.location.href='upgrade-browser.html';</script>
<![endif]-->
</head>

<body class="user-select">
<section class="container-fluid">
  <header>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false"> <span class="sr-only">切换导航</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
          <a class="navbar-brand" href="/">YlsatCMS</a> </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="">消息 <span class="badge">1</span></a></li>
            <li class="dropdown"> <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">admin <span class="caret"></span></a>
              <ul class="dropdown-menu dropdown-menu-left">
                <li><a title="查看或修改个人信息" data-toggle="modal" data-target="#seeUserInfo">个人信息</a></li>
                <li><a title="查看您的登录记录" data-toggle="modal" data-target="#seeUserLoginlog">登录记录</a></li>
              </ul>
            </li>
            <li><a href="login.html" onClick="if(!confirm('是否确认退出？'))return false;">退出登录</a></li>
            <li><a data-toggle="modal" data-target="#WeChat">帮助</a></li>
          </ul>
          <form action="" method="post" class="navbar-form navbar-right" role="search">
            <div class="input-group">
              <input type="text" class="form-control" autocomplete="off" placeholder="键入关键字搜索" maxlength="15">
              <span class="input-group-btn">
              <button class="btn btn-default" type="submit">搜索</button>
              </span> </div>
          </form>
        </div>
      </div>
    </nav>
  </header>
  <div class="row">
    <aside class="col-sm-3 col-md-2 col-lg-2 sidebar">
      <ul class="nav nav-sidebar">
        <li><a href="index.html">报告</a></li>
      </ul>
      <ul class="nav nav-sidebar">
        <li><a href="article.html">文章</a></li>
        <li><a href="notice.html">公告</a></li>
        <li><a href="comment.html">评论</a></li>
        <li><a data-toggle="tooltip" data-placement="top" title="网站暂无留言功能">留言</a></li>
      </ul>
      <ul class="nav nav-sidebar">
        <li class="active"><a href="category.html">栏目</a></li>
        <li><a class="dropdown-toggle" id="otherMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">其他</a>
          <ul class="dropdown-menu" aria-labelledby="otherMenu">
            <li><a href="flink.html">友情链接</a></li>
            <li><a href="loginlog.html">访问记录</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav nav-sidebar">
        <li><a class="dropdown-toggle" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">用户</a>
          <ul class="dropdown-menu" aria-labelledby="userMenu">
            <li><a href="#">管理用户组</a></li>
            <li><a href="manage-user.html">管理用户</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="loginlog.html">管理登录日志</a></li>
          </ul>
        </li>
        <li><a class="dropdown-toggle" id="settingMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">设置</a>
          <ul class="dropdown-menu" aria-labelledby="settingMenu">
            <li><a href="setting.html">基本设置</a></li>
            <li><a href="readset.html">用户设置</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">安全配置</a></li>
            <li role="separator" class="divider"></li>
            <li class="disabled"><a>扩展菜单</a></li>
          </ul>
        </li>
      </ul>
    </aside>
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-lg-10 col-md-offset-2 main" id="main">
      <h1 class="page-header">修改栏目</h1>
      <form action="{{ url_for("blue.category_update",titlename=articlelist.block_article) }}" method="post">
        <div class="form-group">
          <label for="category-name">栏目名称</label>
          <input type="text" id="category-name" name="name" value="{{ articlelist.block_article }}" class="form-control" placeholder="在此处输入栏目名称" required autocomplete="off">
          <span class="prompt-text">这将是它在站点上显示的名字。</span> </div>
        <div class="form-group">
          <label for="category-alias">栏目别名</label>
          <input type="text" id="category-alias" name="alias" value="无" class="form-control" placeholder="在此处输入栏目别名" required autocomplete="off">
          <span class="prompt-text">“别名”是在URL中使用的别称，它可以令URL更美观。通常使用小写，只能包含字母，数字和连字符（-）。</span> </div>
        <div class="form-group">
          <label for="category-fname">父节点</label>
          <select id="category-fname" class="form-control" name="fid">
            <option value="0" selected>无</option>
              {% for foo in data %}
              <option value="{{ foo.block_article }}">{{ foo.block_article }}</option>
              {% endfor %}

          </select>
          <span class="prompt-text">栏目是有层级关系的，您可以有一个“音乐”分类目录，在这个目录下可以有叫做“流行”和“古典”的子目录。</span> </div>
        <div class="form-group">
          <label for="category-keywords">关键字</label>
          <input type="text" id="category-keywords" name="keywords" value="HTML,CSS+DIV,JavaScript,jQuery" class="form-control" placeholder="在此处输入栏目关键字" autocomplete="off">
          <span class="prompt-text">关键字会出现在网页的keywords属性中。</span> </div>
        <div class="form-group">
          <label for="category-describe">描述</label>
          <textarea class="form-control" id="category-describe" name="describe" rows="4" autocomplete="off">这是栏目的描述这是栏目的描述这是栏目的描述这是栏目的描述</textarea>
          <span class="prompt-text">描述会出现在网页的description属性中。</span> </div>
        <button class="btn btn-primary" type="submit" name="submit">更新</button>
      </form>
    </div>
  </div>
</section>
<!--个人信息模态框-->
<div class="modal fade" id="seeUserInfo" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <form action="" method="post">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" >个人信息</h4>
        </div>
        <div class="modal-body">
          <table class="table" style="margin-bottom:0px;">
            <thead>
              <tr> </tr>
            </thead>
            <tbody>
              <tr>
                <td wdith="20%">姓名:</td>
                <td width="80%"><input type="text" value="王雨" class="form-control" name="truename" maxlength="10" autocomplete="off" /></td>
              </tr>
              <tr>
                <td wdith="20%">用户名:</td>
                <td width="80%"><input type="text" value="admin" class="form-control" name="username" maxlength="10" autocomplete="off" /></td>
              </tr>
              <tr>
                <td wdith="20%">电话:</td>
                <td width="80%"><input type="text" value="18538078281" class="form-control" name="usertel" maxlength="13" autocomplete="off" /></td>
              </tr>
              <tr>
                <td wdith="20%">旧密码:</td>
                <td width="80%"><input type="password" class="form-control" name="old_password" maxlength="18" autocomplete="off" /></td>
              </tr>
              <tr>
                <td wdith="20%">新密码:</td>
                <td width="80%"><input type="password" class="form-control" name="password" maxlength="18" autocomplete="off" /></td>
              </tr>
              <tr>
                <td wdith="20%">确认密码:</td>
                <td width="80%"><input type="password" class="form-control" name="new_password" maxlength="18" autocomplete="off" /></td>
              </tr>
            </tbody>
            <tfoot>
              <tr></tr>
            </tfoot>
          </table>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
          <button type="submit" class="btn btn-primary">提交</button>
        </div>
      </div>
    </form>
  </div>
</div>
<!--个人登录记录模态框-->
<div class="modal fade" id="seeUserLoginlog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" >登录记录</h4>
      </div>
      <div class="modal-body">
        <table class="table" style="margin-bottom:0px;">
          <thead>
            <tr>
              <th>登录IP</th>
              <th>登录时间</th>
              <th>状态</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>::1:55570</td>
              <td>2016-01-08 15:50:28</td>
              <td>成功</td>
            </tr>
            <tr>
              <td>::1:64377</td>
              <td>2016-01-08 10:27:44</td>
              <td>成功</td>
            </tr>
            <tr>
              <td>::1:64027</td>
              <td>2016-01-08 10:19:25</td>
              <td>成功</td>
            </tr>
            <tr>
              <td>::1:57081</td>
              <td>2016-01-06 10:35:12</td>
              <td>成功</td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">朕已阅</button>
      </div>
    </div>
  </div>
</div>
<!--微信二维码模态框-->
<div class="modal fade user-select" id="WeChat" tabindex="-1" role="dialog" aria-labelledby="WeChatModalLabel">
  <div class="modal-dialog" role="document" style="margin-top:120px;max-width:280px;">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="WeChatModalLabel" style="cursor:default;">微信扫一扫</h4>
      </div>
      <div class="modal-body" style="text-align:center"> <img src="/static/images/weixin.jpg" alt="" style="cursor:pointer"/> </div>
    </div>
  </div>
</div>
<!--提示模态框-->
<div class="modal fade user-select" id="areDeveloping" tabindex="-1" role="dialog" aria-labelledby="areDevelopingModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="areDevelopingModalLabel" style="cursor:default;">该功能正在日以继夜的开发中…</h4>
      </div>
      <div class="modal-body"> <img src="/static/images/baoman/baoman_01.gif" alt="深思熟虑" />
        <p style="padding:15px 15px 15px 100px; position:absolute; top:15px; cursor:default;">很抱歉，程序猿正在日以继夜的开发此功能，本程序将会在以后的版本中持续完善！</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">朕已阅</button>
      </div>
    </div>
  </div>
</div>
<!--右键菜单列表-->
<div id="rightClickMenu">
  <ul class="list-group rightClickMenuList">
    <li class="list-group-item disabled">欢迎访问异清轩博客</li>
    <li class="list-group-item"><span>IP：</span>172.16.10.129</li>
    <li class="list-group-item"><span>地址：</span>河南省郑州市</li>
    <li class="list-group-item"><span>系统：</span>Windows10 </li>
    <li class="list-group-item"><span>浏览器：</span>Chrome47</li>
  </ul>
</div>
<script src="/static/js/bootstrap.min.js"></script>
<script src="/static/js/admin-scripts.js"></script>
</body>
</html>